title: Kadir Yavuz Kurt's Homepage
page-top-title: Kadir Yavuz Kurt
top-section-bg-text: Control Systems, Robotics, and AI
home-subtitle: Kadir Yavuz Kurt&ensp;|&ensp;Kadir Yavuz Kurt
copyright-text: '&copy; Kadir Yavuz Kurt 2024. All Rights Reserved.'
